from src.schemas.common import utc_now_iso
from src.schemas.place import PlaceOption, PlaceSearchRequest, RestaurantOption

from .base import PlacesProvider


class MockPlacesProvider(PlacesProvider):
    name = "MockPlacesProvider"

    async def search_places(self, request: PlaceSearchRequest) -> list[PlaceOption]:
        fetched_at = utc_now_iso()
        places = [
            PlaceOption(
                id="place_red_fort",
                name="Red Fort",
                category="landmark",
                address="Netaji Subhash Marg, Lal Qila, Old Delhi",
                lat=28.6562,
                lng=77.2410,
                rating=4.5,
                price_level="$",
                opening_hours={"mon_sun": "09:30-16:30", "closed": ["Monday"]},
                estimated_visit_duration_minutes=120,
                booking_required=True,
                booking_url="https://example.com/attractions/red-fort",
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Major Mughal landmark with strong cultural and photography value.",
            ),
            PlaceOption(
                id="place_jama_masjid",
                name="Jama Masjid",
                category="religious",
                address="Meena Bazaar, Jama Masjid, Old Delhi",
                lat=28.6507,
                lng=77.2334,
                rating=4.5,
                price_level="$",
                opening_hours={"mon_sun": "07:00-18:30"},
                estimated_visit_duration_minutes=75,
                booking_required=False,
                booking_url=None,
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Historic mosque and rooftop-photo neighborhood near Old Delhi lanes.",
            ),
            PlaceOption(
                id="place_humayun_tomb",
                name="Humayun's Tomb",
                category="landmark",
                address="Mathura Road, Nizamuddin East, New Delhi",
                lat=28.5933,
                lng=77.2507,
                rating=4.6,
                price_level="$$",
                opening_hours={"mon_sun": "06:00-18:00"},
                estimated_visit_duration_minutes=105,
                booking_required=True,
                booking_url="https://example.com/attractions/humayuns-tomb",
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Excellent golden-hour photography and UNESCO heritage context.",
            ),
            PlaceOption(
                id="place_lodhi_garden",
                name="Lodhi Garden",
                category="nature",
                address="Lodhi Road, New Delhi",
                lat=28.5931,
                lng=77.2197,
                rating=4.5,
                price_level="Free",
                opening_hours={"mon_sun": "06:00-20:00"},
                estimated_visit_duration_minutes=90,
                booking_required=False,
                booking_url=None,
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Relaxed green space with tomb architecture and photography stops.",
            ),
            PlaceOption(
                id="place_india_gate",
                name="India Gate",
                category="landmark",
                address="Kartavya Path, India Gate, New Delhi",
                lat=28.6129,
                lng=77.2295,
                rating=4.6,
                price_level="Free",
                opening_hours={"mon_sun": "Open 24 hours"},
                estimated_visit_duration_minutes=45,
                booking_required=False,
                booking_url=None,
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Classic Delhi photo stop that pairs efficiently with central sights.",
            ),
            PlaceOption(
                id="place_dilli_haat",
                name="Dilli Haat INA",
                category="shopping",
                address="Sri Aurobindo Marg, INA, New Delhi",
                lat=28.5733,
                lng=77.2097,
                rating=4.3,
                price_level="$",
                opening_hours={"mon_sun": "10:30-22:00"},
                estimated_visit_duration_minutes=120,
                booking_required=False,
                booking_url="https://example.com/attractions/dilli-haat",
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Crafts, textiles, food stalls, and a good shopping add-on.",
            ),
            PlaceOption(
                id="place_khan_market",
                name="Khan Market",
                category="shopping",
                address="Khan Market, Rabindra Nagar, New Delhi",
                lat=28.6006,
                lng=77.2273,
                rating=4.4,
                price_level="$$$",
                opening_hours={"mon_sun": "10:00-23:00"},
                estimated_visit_duration_minutes=90,
                booking_required=False,
                booking_url=None,
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Upscale cafes, bookstores, boutiques, and relaxed evening shopping.",
            ),
        ]
        if request.limit:
            return places[: request.limit]
        return places

    async def get_place_details(self, place_id: str) -> PlaceOption:
        places = await self.search_places(PlaceSearchRequest(destination="Delhi"))
        for place in places:
            if place.id == place_id:
                return place
        raise KeyError(place_id)

    async def search_restaurants(self, request: PlaceSearchRequest) -> list[RestaurantOption]:
        fetched_at = utc_now_iso()
        restaurants = [
            RestaurantOption(
                id="restaurant_saravana",
                name="Saravana Bhavan Connaught Place",
                cuisine=["South Indian", "Vegetarian"],
                dietary_tags=["vegetarian", "vegan-friendly"],
                address="P-13, Connaught Circus, New Delhi",
                lat=28.6326,
                lng=77.2197,
                rating=4.2,
                price_level="$",
                opening_hours={"mon_sun": "08:00-22:30"},
                reservation_url="https://example.com/restaurants/saravana-bhavan",
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Reliable vegetarian meals near the central hotel cluster.",
            ),
            RestaurantOption(
                id="restaurant_sattvik",
                name="Sattvik",
                cuisine=["North Indian", "Vegetarian"],
                dietary_tags=["vegetarian", "jain-friendly"],
                address="Select Citywalk, Saket, New Delhi",
                lat=28.5288,
                lng=77.2197,
                rating=4.3,
                price_level="$$",
                opening_hours={"mon_sun": "12:00-23:00"},
                reservation_url="https://example.com/restaurants/sattvik",
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Polished vegetarian dining with broad North Indian options.",
            ),
            RestaurantOption(
                id="restaurant_cafe_lota",
                name="Cafe Lota",
                cuisine=["Regional Indian", "Cafe"],
                dietary_tags=["vegetarian-friendly"],
                address="National Crafts Museum, Pragati Maidan, New Delhi",
                lat=28.6138,
                lng=77.2427,
                rating=4.4,
                price_level="$$",
                opening_hours={"tue_sun": "08:00-20:30", "closed": ["Monday"]},
                reservation_url="https://example.com/restaurants/cafe-lota",
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Scenic cafe choice with regional vegetarian dishes near culture stops.",
            ),
            RestaurantOption(
                id="restaurant_bikanervala",
                name="Bikanervala Karol Bagh",
                cuisine=["Indian", "Street food", "Vegetarian"],
                dietary_tags=["vegetarian"],
                address="Karol Bagh, New Delhi",
                lat=28.6510,
                lng=77.1909,
                rating=4.1,
                price_level="$",
                opening_hours={"mon_sun": "08:00-23:00"},
                reservation_url=None,
                provider=self.name,
                fetched_at=fetched_at,
                why_recommended="Budget-friendly vegetarian snacks and sweets.",
            ),
        ]
        return restaurants[: request.limit] if request.limit else restaurants
